tags: [
    {y: 0.0, x: 0.0, z: 0.0},
    {y: -0.125, x: 0.72, z: 0.0},
    {y: -0.945, x: 0.15, z: 0.0},
    {y: -0.155, x: -0.89, z: 0.0},
    {x: 3.04, y: -0.01, z: -0.965},
    {x: 0.025, y: 1.28, z: 0}
]